baseURL = 'https://ezce.github.io/ez80-docs/'
languageCode = 'en-us'
title = 'eZ80 docs'
theme = "hugo-geekdoc"
ignorefiles = [ "content/instructions/readme.md", "content/syscalls/readme.md", "content/memory/readme.md" ]

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
 
[params]
  geekdocBreadcrumb = true
  geekdocRepo = "https://github.com/EzCE/ez80-docs"
  geekdocEditPath = "edit/main"

[params.geekdocContentLicense]
    name = "AGPL-3.0"
    link = "https://www.gnu.org/licenses/agpl-3.0.en.html"
